language: php
php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - hhvm

matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm

install:
  - composer install

script:
  - mkdir -p build/logs
  - phpunit

after_success:
  - travis_retry php vendor/bin/coveralls